name: Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install sdl and glfw via vcpkg
      run: |
         python tools/vcpkg_install_third_parties.py
         cd vcpkg
         .\vcpkg integrate install
         cd ..

    - name: Configure
      run: |
         mkdir build
         cd build
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=D:/a/hello_imgui/hello_imgui/vcpkg/scripts/buildsystems/vcpkg.cmake -DHELLOIMGUI_USE_SDL_OPENGL3=ON -DHELLOIMGUI_USE_GLFW_OPENGL3=ON -DHELLOIMGUI_USE_GLAD=ON -DHELLOIMGUI_BUILD_DOCS=ON ..

    - name: Build
      working-directory: build
      run: |
         cmake --build .
